local AddName, AddonTable = ...

local L = AddonTable.RegisterLocale("koKR", true)

L["SpellPowerModifiers"] = "Spell Power Modifiers"
L["ShadowWeaving"] = "어둠의 매듭"
L["Misery"] = "불행"
L["EbonPlague"] = "칠흑의 역병"
L["ThundraStalker"] = "동토의 추적자"
L["RageofRivendare"] = "리븐데어의 분노"
L["SurvivalofFittest"] = "적자 생존"
L["FaerieFire"] = "요정의 불꽃"
L["InsectSwarm"] = "곤충 떼"
L["EarthAndMoon"] = "대지와 달"
L["ImprovedFaerieFire"] = "요정의 불꽃 연마"
L["HuntersMark"] = "사냥꾼의 징표"	
L["ScorpidSting"] = "전갈 쐐기"
L["WintersChill"] = "혹한의 추위"
L["ImprovedScorch"] = "불태우기 연마"
L["FireVulnerability"] = "화염 저항력 약화"
L["HeartCrusader"] = "성전사의 심장"
L["Crusade"] = "성전"
L["Vengeance"] = "복수"
L["Hemorrhage"] = "과다출혈"
L["SavageCombat"] = "야만적인 전투"
L["MasterPoisoner"] = "독의 대가"
L["ExposeArmor"] = "약점 노출"
L["Stormstrike"] = "폭풍의 일격"
L["TotemOfWrath"] = "격노의 토템"
L["SunderArmor"] = "방어구 가르기"
L["BloodFrenzy"] = "피의 광기"
L["ShadowVulnerability"] = "암흑 저항력 약화"
L["ShadowMastery"] = "암흑 마법 전문화"
L["CurseofElements"] = "원소의 저주"
L["CurseOfWeak"] = "무력화 저주"

L["TipsAndInfo"] = "팁과 정보!"
L["SinLive"] = "SinLive™ Stat! 이 스탯은 현재 대상과 상호작용하고 스케일링됩니다!"
L["NPCPlus3"] = "+3레벨"
L["NPC1to5"] = "+1~ +5레벨"
L["NPCAnyLevel"] = "아무 레벨"
L["NPCSameLevel"] = "동일 레벨"	
L["DefaultValueText"] = "기본값"
L["ScalingText"] = "대상 스케일링"

L["CommonScaling"] = "This stat scales with on other stats"
L["Enhanced_BaseTooltip"] = "Enhanced provides the best accuracy by including talents, buffs, gems, enchants and much more " .. "Basic shows the basic value as displayed on the character panel, without any additions"
L["Percent_RatingTooltip"] = "Percentage displays the percentage value of this stat " .. "Rating displays the rating value of this stat"
L["Main_Off_HandTooltip"] = "Main-hand displays the Main-Hand value of this stat " .. "Off-hand displays the Off-Hand value of this stat"
L["Level_Same_BossTooltip"] = "Same Level displays the value against an NPC of the same level as yours " .. "Boss Level displays the value against an NPC of 1 to 5 level higher than yours"
L["Crit_Damage_TakenTooltip"] = "Crit Taken displays the reduction in periodic damage and in the chance to be critically hit " .. "Damage Taken displays the reduction in mana-drains effects and in the damage of critical strikes"
L["Chance_ReductionTooltip"] = "Chance displays the chance to be critically hit " .. "Reduction displays the reduction value to reach Crit immunity"
L["Total_RatingTooltip"] = "Total displays the total Defense value, that includes the base and the bonus " .. "Rating displays the rating value of this stat"
L["Max_Average_DamageTooltip"] = "Max displays maximum damage value " .. "Average switches from max values to average values"
L["Regen_Normal_CastingTooltip"] = "Normal displays the mana regeneration outside of the 5-second rule, while not casting " .. "Casting displays the mana regeneration while casting"
L["World_RealmTooltip"] = "Realm displays the average latency of the connection from your computer to the Blizzard server in milliseconds" .. "World displays the in-game latency of the connection from your computer to the Game World"
L["Main_Off_AutoTooltip"] = "Main-hand displays the Main-Hand value of this stat " .. "Off-hand displays the Off-Hand value of this stat " .. "Auto automatically detects if you're wielding a 1H or 2H and displays the stat accordingly"
L["Display_MainHandTooltip"] = "Main-Hand Only disables the automatic display of the Off-hand value, if applicable"
L["Display_AverageTooltip"] = "Average switches from max to average values"
L["Display_BasicTooltip"] = "Basic shows the basic value as displayed on the character panel, without any additions"

L["AP"] = "전투력"
L["APAbrev"] = "전투력"
L["APMenu"] = "전투력"
L["APTip"] = ""
L["APDescription"] = "근접 전투력\n붉은색 값은 디버프에 영향받는 중임을 알려줍니다."

L["DMG"] = "데미지"
L["DMGAbrev"] = "데미지"
L["DMGMenu"] = "데미지"
L["DMGTip"] = ""
L["DMGDescription"] = "붉은색 값은 디버프에 영향받는 중임을 알려줍니다." 

L["mDPS"] = "DPS"
L["mDPSAbrev"] = "DPS"
L["mDPSMenu"] = "DPS"
L["mDPSTip"] = ""
L["mDPSDescription"] = "붉은색 값은 디버프에 영향받는 중임을 알려줍니다.\n이 스탯은 공속과 데미지에 의한 보정을 받습니다."

L["Crit"] = "치명"
L["CritAbrev"] = "치명"
L["CritMenu"] = "치명타 확률"
L["CritTip"] = ""
L["CritDescription"] = "근접 치명타 확률. \nPvP 특정 치명 특성에 의한 치명타 확률은 현재 확률 옆에 색칠되어 나옵니다."

L["CritBoss"] = "치명+"
L["CritBossAbrev"] = "치명+"
L["CritBossMenu"] = "치명 vs 보스"
L["CritBossTip"] = ""
L["CritBossDescription"] = "PVE에서 높은레벨의NPC(우두머리)에 대한 근접 치명타 값. \n모든 치명타 보정 오라를 포함합니다."

L["CritCap"] = "치명 캡"
L["CritCapAbrev"] = "치명캡"
L["CritCapMenu"] = "치명타 캡"
L["CritCapTip"] = ""
L["CritCapDescription"] = "보스에 대한 치명타 캡을 표시합니다. \n이 스탯은 사용중인 무기에 의해 스케일링됩니다.\n붉은색 치명타캡 값은 치명타 캡에 도달했다는 것을 알려줍니다."

L["Hit"] = "적중"
L["HitAbrev"] = "적중"
L["HitMenu"] = "적중"
L["HitTip"] = ""
L["HitDescription"] = "근접 적중을 표시합니다.(퍼센트, 수치, 모두) \n녹색 값은 적중값 목표를 달성했음을 알려줍니다."

L["HasteMelee"] = "가속"
L["HasteMeleeAbrev"] = "가속"
L["HasteMeleeMenu"] = "가속"
L["HasteMeleeTip"] = ""
L["HasteMeleeDescription"] = "근접 가속을 표시합니다.(퍼센트, 수치, 모두)"

L["weaponSpeed"] = "공격속도"
L["weaponSpeedAbrev"] = "공속"
L["weaponSpeedMenu"] = "공격속도"
L["weaponSpeedTip"] = ""
L["weaponSpeedDescription"] = "근접 공격속도를 표시합니다. (주무기, 보조무기, 자동)"

L["Expertise"] = "숙련도"
L["ExpertiseAbrev"] = "숙련"
L["ExpertiseMenu"] = "숙련도"
L["ExpertiseTip"] = ""
L["ExpertiseDescription"] = "공격이 회피되거나 무기막기에 막힐 (확률, 수치, 모두)\n녹색 값은 숙련도값 목표를 달성했음을 알려줍니다."

L["ArmorPen"] = "방어구 관통"
L["ArmorPenAbrev"] = "방관"
L["ArmorPenMenu"] = "방어구 관통"
L["ArmorPenTip"] = ""
L["ArmorPenDescription"] = "대상의 방어도가 무시될 (확률, 수치, 모두)."

L["NPCArmor"] = "방어력+"
L["NPCArmorAbrev"] = "방어력+"
L["NPCArmorMenu"] = "보스 방어력"
L["NPCArmorTip"] = ""
L["NPCArmorDescription"] = "보스NPC의 방어도값. \n방어도값을 표시하려면 대상을 선택해야 합니다."

L["BossReduc"] = "데미지-"
L["BossReducAbrev"] = "데미지-"
L["BossReducMenu"] = "데미지 감소"
L["BossReducTip"] = ""
L["BossReducDescription"] = "보스NPC의 방어도에 기반한 물리피해 감소 비율\n일반몹을 대상잡을 경우, 방어력 감소 디버프의 총 값이 표시됩니다.\n감소값을 표시하려면 대상을 선택해야 합니다.\n" .. L["ScalingText"] .. L["NPCPlus3"].." : " .. L["SunderArmor"]..", " .. L["ExposeArmor"]..", " .. L["FaerieFire"]..", " .. L["CurseOfWeak"]

L["MeleeMiss"] = "빗맞힘"
L["MeleeMissAbrev"] = "빗맞힘"
L["MeleeMissMenu"] = "빗맞힘률"
L["MeleeMissTip"] = ""
L["MeleeMissDescription"] = "(동일레벨, 보스레벨, 모두) NPC에 대한 근접무기의 빗맞힘률."

L["Avoidance"] = "회피"
L["AvoidanceAbrev"] = "회피"
L["AvoidanceMenu"] = "회피율"
L["AvoidanceTip"] = ""
L["AvoidanceDescription"] = "Chance to avoid Crushing Blows " .. "Avoidance value in green indicates that you are uncrushable"

L["Crushing"] = "Crushing"
L["CrushingAbrev"] = "Crush"
L["CrushingMenu"] = "Crushing"
L["CrushingTip"] = ""
L["CrushingDescription"] = "Chance to hit by a Crushing Blow " .. "Crushing value in green indicates that you are uncrushable"

L["CritReceived"] = "치명-"
L["CritReceivedAbrev"] = "치명-"
L["CritReceivedMenu"] = "치명 이뮨" 
L["CritReceivedTip"] = "" .. "Crtically Hit value in red indicates that you are under the critical hit cap" .. L["DefaultValueText"] .. L["NPCPlus3"] .. L["ScalingText"] .. L["NPCAnyLevel"] .. L["SurvivalofFittest"]

L["Resilience"] = "Resilience"
L["ResilienceAbrev"] = "Res"
L["ResilienceMenu"] = "Resilience"
L["ResilienceTip"] = ""
L["ResilienceDescription"] = "Resilience displayed in critical taken, damage taken or both"

L["Armor"] = "방어력"
L["ArmorAbrev"] = "방어"
L["ArmorMenu"] = "방어력"
L["ArmorTip"] = ""
L["ArmorDescription"] = "Effective Armor including its modifiers " .. "Armor value in red indicates that you are affected by a debuff related to this stat"	

L["Mitigation"] = "Mitigation"
L["MitigationAbrev"] = "Mit"
L["MitigationMenu"] = "Mitigation"
L["MitigationTip"] = ""
L["MitigationDescription"] = "Percentage of damage reduction " .. "Mitigation value in green indicates that you have reached the Mitigation cap"

L["DefenseStat"] = "Defense"
L["DefenseStatAbrev"] = "Def"
L["DefenseStatMenu"] = "Defense"
L["DefenseStatTip"] = ""
L["DefenseStatDescription"] = "Defense displayed in total, rating or both " .. "Defense value in green indicates that you have reached the Defense cap against a raid boss"

L["HitReduction"] = "Hit-"
L["HitReductionAbrev"] = "Hit-"
L["HitReductionMenu"] = "Hit Reduction"
L["HitReductionTip"] = ""
L["HitReductionDescription"] = "Percentage reduction to be hit by physical attacks from talents and debuffs "

L["Dodge"] = "회피"
L["DodgeAbrev"] = "Dod"
L["DodgeMenu"] = "Dodge"
L["DodgeTip"] = ""
L["DodgeDescription"] = "Chance to Dodge an attack, displayed in percentage, rating or both"

L["Parry"] = "무기막기"
L["ParryAbrev"] = "Par"
L["ParryMenu"] = "Parry"
L["ParryTip"] = ""
L["ParryDescription"] = "Chance to Parry an attack, displayed in percentage, rating or both"

L["Block"] = "Block"
L["BlockAbrev"] = "Blo"
L["BlockMenu"] = "Block"
L["BlockTip"] = ""
L["BlockDescription"] = "Chance to Block an attack, displayed in percentage, rating or both"

L["RAP"] = "원거리 전투력"
L["RAPAbrev"] = "원거리전투력"
L["RAPMenu"] = "전투력"
L["RAPTip"] = ""
L["RAPDescription"] = "원거리 전투력\n붉은색 값은 디버프에 영향받는 중임을 알려줍니다.\n녹색 값은 사냥꾼의 징표가 대상에 적용되었다는 것을 알려줍니다."

L["RDMG"] = "원거리 데미지"
L["RDMGAbrev"] = "원거리데미지"
L["RDMGMenu"] = "데미지"
L["RDMGTip"] = ""
L["RDMGDescription"] = "붉은색 값은 디버프에 영향받는 중임을 알려줍니다."

L["rDPS"] = "원거리 DPS"
L["rDPSAbrev"] = "원거리DPS"
L["rDPSMenu"] = "DPS"
L["rDPSTip"] = ""
L["rDPSDescription"] = "DPS를 표시합니다. (최대, 평균, 모두) \n붉은색 값은 디버프에 영향받는 중임을 표시해줍니다. \n이 스탯은 공속과 데미지에 의한 보정을 받습니다."

L["RangedCrit"] = "원거리 치명"
L["RangedCritAbrev"] = "원거리치명"
L["RangedCritMenu"] = "치명타율"
L["RangedCritTip"] = ""
L["RangedCritDescription"] = "치명타 확률을 표시합니다(퍼센트, 수치, 모두). \nPvP 특정 치명 특성에 의한 치명타 확률은 현재 확률 옆에 색칠되어 나옵니다."

L["RangedCritBoss"] = "원거리 치명+"
L["RangedCritBossAbrev"] = "원거리치명+"
L["RangedCritBossMenu"] = "치명타율 vs 보스"
L["RangedCritBossTip"] = ""
L["RangedCritBossDescription"] = "PVE에서 높은레벨의NPC(우두머리)에 대한 원거리 치명타 값. \n모든 치명타 보정 오라를 포함합니다."

L["RangedHit"] = "원거리 적중"
L["RangedHitAbrev"] = "원거리적중"
L["RangedHitMenu"] = "적중"
L["RangedHitTip"] = ""
L["RangedHitDescription"] = "원거리 적중을 표시합니다.(퍼센트, 수치, 모두) \n녹색 값은 적중값 목표를 달성했음을 알려줍니다."

L["HasteRanged"] = "원거리 가속"
L["HasteRangedAbrev"] = "원거리가속"
L["HasteRangedMenu"] = "가속"
L["HasteRangedTip"] = ""
L["HasteRangedDescription"] = "원거리 가속을 표시합니다.(퍼센트, 수치, 모두)"

L["RangedPen"] = "원거리 방관"
L["RangedPenAbrev"] = "원거리방관"
L["RangedPenMenu"] = "방관"
L["RangedPenTip"] = ""
L["RangedPenDescription"] = "원거리 공격으로 대상의 방어도를 무시할 확률입니다."

L["rangedSpeed"] = "원거리 공격 속도"
L["rangedSpeedAbrev"] = "원거리공속"
L["rangedSpeedMenu"] = "공격 속도"
L["rangedSpeedTip"] = ""
L["rangedSpeedDescription"] = "착용 중인 원거리 무기의 공격 속도입니다."

L["RangedMiss"] = "원거리 빗맞힘률"
L["RangedMissAbrev"] = "원거리빗맞힘"
L["RangedMissMenu"] = "빗맞힘률"
L["RangedMissTip"] = ""
L["RangedMissDescription"] = "원거리 빗맞힘률을 표시합니다. (동일 레벨, 보스 레벨, 모두)"

L["Fire"] = "화염"
L["FireAbrev"] = "화염"
L["FireMenu"] = "화염 주문력"
L["FireTip"] = ""
L["FireDescription"] = "화염 주문력"

L["Frost"] = "냉기"
L["FrostAbrev"] = "냉기"
L["FrostMenu"] = "냉기 주문력"
L["FrostTip"] = ""
L["FrostDescription"] = "비전 주문력"

L["Arcane"] = "비전"
L["ArcaneAbrev"] = "비전"
L["ArcaneMenu"] = "비전 주문력"
L["ArcaneTip"] = ""
L["ArcaneDescription"] = "비전 주문력"

L["Shadow"] = "암흑"
L["ShadowAbrev"] = "암흑"
L["ShadowMenu"] = "암흑 주문력"
L["ShadowTip"] = ""
L["ShadowDescription"] = "암흑 주문력"

L["Nature"] = "자연"
L["NatureAbrev"] = "자연"
L["NatureMenu"] = "자연 주문력"
L["NatureTip"] = ""
L["NatureDescription"] = "자연 주문력"

L["Healing"] = "치유"
L["HealingAbrev"] = "힐"
L["HealingMenu"] = "주문 치유량"
L["HealingTip"] = ""
L["HealingDescription"] = "주문 치유량"

L["Holy"] = "신성"
L["HolyAbrev"] = "신성"
L["HolyMenu"] = "신성 주문력"
L["HolyTip"] = ""
L["HolyDescription"] = "신성 데미지"

L["SpellCrit"] = "주문 치명"
L["SpellCritAbrev"] = "주문치명"
L["SpellCritMenu"] = "치명타 확률"
L["SpellCritTip"] = ""
L["SpellCritDescription"] = "치명타 확률을 표시합니다(퍼센트, 수치, 모두). \nPvP 특정 치명 특성에 의한 치명타 확률은 현재 확률 옆에 색칠되어 나옵니다."

L["SpellCritBoss"] = "주문 치명+"
L["SpellCritBossAbrev"] = "주문치명+"
L["SpellCritBossMenu"] = "치명 vs 보스"
L["SpellCritBossTip"] = ""
L["SpellCritBossDescription"] = "PVE에서 높은레벨의NPC(우두머리)에 대한 주문 치명타 값. \n모든 치명타 보정 오라를 포함합니다."

L["SpellHit"] = "주문 적중"
L["SpellHitAbrev"] = "주문적중"
L["SpellHitMenu"] = "적중"
L["SpellHitTip"] = ""
L["SpellHitDescription"] = "주문 적중을 표시합니다. (퍼센트, 수치, 모두)"

L["HasteCaster"] = "주문 가속"
L["HasteCasterAbrev"] = "주문가속"
L["HasteCasterMenu"] = "가속"
L["HasteCasterTip"] = ""
L["HasteCasterDescription"] = "주문 가속을 표시합니다. (퍼센트, 수치, 모두)"

L["SpellPenetration"] = "주문 관통"
L["SpellPenetrationAbrev"] = "주문관통"
L["SpellPenetrationMenu"] = "관통"
L["SpellPenetrationTip"] = ""
L["SpellPenetrationDescription"] = "주문이 타겟의 주문 저항을 무시할 확률입니다."

L["SpellMiss"] = "주문 빗맞힘률"
L["SpellMissAbrev"] = "주문빗맞힘"
L["SpellMissMenu"] = "빗맞힘률"
L["SpellMissTip"] = ""
L["SpellMissDescription"] = "주문 빗맞힘률을 표시합니다. (동일 레벨, 보스 레벨, 모두)"

L["ManaRegen"] = "마젠2"
L["ManaRegenAbrev"] = "마젠2"
L["ManaRegenMenu"] = "마젠2"
L["ManaRegenTip"] = ""
L["ManaRegenDescription"] = "2초당 마나 회복량을 표시합니다."

L["MP5"] = "마젠5"
L["MP5Abrev"] = "마젠5"
L["MP5Menu"] = "마젠5"
L["MP5Tip"] = ""
L["MP5Description"] = "5초당 마나 회복량을 표시합니다."

L["FireResist"] = "화염 저항"
L["FireResistAbrev"] = "화저"
L["FireResistMenu"] = "화염 저항"
L["FireResistTip"] = ""
L["FireResistDescription"] = "화염 주문 데미지에 대한 저항값을 표시합니다."

L["FrostResist"] = "냉기 저항"
L["FrostResistAbrev"] = "냉저"
L["FrostResistMenu"] = "냉기 저항"
L["FrostResistTip"] = ""
L["FrostResistDescription"] = "냉기 주문 데미지에 대한 저항값을 표시합니다."

L["ShadowResist"] = "암흑 저항"
L["ShadowResistAbrev"] = "암저"
L["ShadowResistMenu"] = "암흑 저항"
L["ShadowResistTip"] = ""
L["ShadowResistDescription"] = "암흑 주문 데미지에 대한 저항값을 표시합니다."

L["ArcaneResist"] = "바전 저항"
L["ArcaneResistAbrev"] = "비저"
L["ArcaneResistMenu"] = "비전 저항"
L["ArcaneResistTip"] = ""
L["ArcaneResistDescription"] = "비전 주문 데미지에 대한 저항값을 표시합니다."

L["NatureResist"] = "자연 저항"
L["NatureResistAbrev"] = "자저"
L["NatureResistMenu"] = "자연 저항"
L["NatureResistTip"] = ""
L["NatureResistDescription"] = "자연 주문 데미지에 대한 저항값을 표시합니다."

L["ItemLevel"] = "아이템 레벨"
L["ItemLevelAbrev"] = "템렙"
L["ItemLevelMenu"] = "아이템 레벨"
L["ItemLevelTip"] = ""
L["ItemLevelDescription"] = "현재 착용 장비의 평균 아이템 레벨을 표시합니다."

L["Speed"] = "이속"
L["SpeedAbrev"] = "이속"
L["SpeedMenu"] = "이동속도"
L["SpeedTip"] = ""
L["SpeedDescription"] = "플레이어의 이동속도를 실시간으로 표시합니다. \n붉은색은 평소보다 느린 것을 나타냅니다."

L["TargetSpeed"] = "대상 이속"
L["TargetSpeedAbrev"] = "이속+"
L["TargetSpeedMenu"] = "대상 이동속도"
L["TargetSpeedTip"] = ""
L["TargetSpeedDescription"] = "대상의 이동속도를 실시간으로 표시합니다. \n붉은색은 평소보다 느린 것을 나타냅니다."

L["Durability"] = "내구도"
L["DurabilityAbrev"] = "내구"
L["DurabilityMenu"] = "내구도"
L["DurabilityTip"] = ""
L["DurabilityDescription"] = "현재 착용중인 장비와 무기의 내구도 퍼센트를 표시합니다."

L["BuffCounter"] = "버프"
L["BuffCounterAbrev"] = "버프"
L["BuffCounterMenu"] = "플레이어 버프"
L["BuffCounterTip"] = ""
L["BuffCounterDescription"] = "플레이어에게 적용된 버프 개수의 총합을 표시합니다."

L["DebuffCounter"] = "디버프"
L["DebuffCounterAbrev"] = "디법"
L["DebuffCounterMenu"] = "대상의 디버프"
L["DebuffCounterTip"] = ""
L["DebuffCounterDescription"] = "플레이어에게 적용된 디버프 개수의 총합을 표시합니다."

L["Lag"] = "핑"
L["LagAbrev"] = "핑"
L["LagMenu"] = "핑"
L["LagTip"] = ""
L["LagDescription"] = "Connection latency (Ping)"

L["FPS"] = "FPS"
L["FPSAbrev"] = "FPS"
L["FPSMenu"] = "FPS"
L["FPSTip"] = ""
L["FPSDescription"] = "Frames per second [FPS]"

L["Money"] = "골드"
L["MoneyAbrev"] = "골"
L["MoneyMenu"] = "골드"
L["MoneyTip"] = ""
L["MoneyDescription"] = "현재 캐릭터가 소유중인 총 골드를 표시합니다."


-- Fonts
L["Default Font"] = "기본 글꼴"
L["Thin"] = "얇게"
L["Thick"] = "굵게"
L["Monochrome"] = "외곽선"
L["Thin Monochrome"] = "얇은 모노크롬"
L["Thick Monochrome"] = "두꺼운 모노크롬"
L["None"] = "없음"



	------------------
	--    Config    --
	------------------

-- Settings tabs
L["HUDMenu"] = "일반"
L["FontsMenu"] = "폰트"
L["DisplayMenu"] = "디스플레이"
L["ProfilesMenu"] = "프로필"

-- Settings HUD
L["SettingsDescription"] = ""
L["HideHUD"] = "숨기기"
L["HideHUDTip"] = "HUD의 위치를 숨기거나, 잠그거나, 리셋합니다. "
L["LockHUD"] = "잠그기"
L["LockHUDTip"] = ""
L["ResetPosition"] = "위치 초기화"
L["ResetPositionTip"] = ""
L["MinimapGroupText"] = "미니맵"
L["Minimap"] = "표시"
L["MinimapTip"] = "미니맵 버튼을 보이기/숨기기. 미니맵 아이콘에 커서를 대면 빠른 접근 가능."

-- Fonts Settings
L["StatFontTip"] = "폰트"
L["StatFontSizeTip"] = "폰트 크기"
L["StatFontFlagsTip"] = "외곽선"

-- Display Settings
L["StatIconsTip"] = "HUD 아이콘 표시"
L["StatIcons"] = "아이콘"
L["StatTextAbreviateTip"] = "스탯 이름 축약"
L["StatTextAbreviate"] = "축약"
L["StatTextCapsTip"] = "대문자 (한국 해당x)"
L["StatTextCaps"] = "모두 대문자"
L["GroupOrderTip"] = "그룹에 의해 스탯을 정렬"
L["GroupOrder"] = "그룹 정렬"
L["VerticalGroupText"] = "정렬 & 간격"
L["VerticalTip"] = "가로 & 세로"
L["Vertical"] = "가로"
L["StatSpacingHTip"] = "가로 간격"
L["StatSpacingVTip"] = "세로 간격"
L["StatAlignmentTip"] = "정렬"
L["StatRowsTip"] = "줄"

-- Minimap
L["LeftClick"] = "퀵메뉴"
L["OpenClose"] = ""
L["RightClick"] = "우클릭"
L["EnableDisable"] = "HUD 켜기/끄기"
L["ShiftRightClick"] = "시프트 + 우클릭"
L["UnlockHUD"] = "HUD 잠금해제"

-- Settings Profile
L["Selected"] = "적용"
L["SelectProfile"] = "프로필 관리: 선택, 생성, 복사, 삭제. 사용중인 프로필 삭제할 때, 다른프로필 선택해야됨."
L["ProfileSelected"] = "프로필"
L["ProfileUsed"] = "현재 사용중인 프로필은 삭제가 불가능합니다."
L["NewProfile"] = "새 프로필"
L["CurrentProfile"] = "현재 프로필"
L["Copy"] = "적용"
L["Delete"] = "삭제"
L["ConfirmDelete"] = "확인"
L["Cancel"] = "취소"
L["ProfileCopyDelete"] = "새 프로필을 선택, 삭제, 복사합니다."

-- Settings Options
L["OptionsTip"] = "확장 옵션"
L["Show"] = "표시"
L["ShowTip"] = ""
L["Enhanced"] = "강화"
L["Basic"] = "기본"
L["Damage"] = "데미지"
L["DamageTaken"] = "받은 데미지"
L["Percentage"] = "퍼센트"
L["Rating"] = "수치"
L["MainHand"] = "주무기"
L["OffHand"] = "보조무기"
L["SameLevel"] = "동일 레벨"
L["BossLevel"] = "보스 레벨"
L["Regen"] = "평상시 회복"
L["OutOfCombat"] = "평상시"
L["Casting"] = "캐스팅"
L["CritTaken"] = "치명타 적중"
L["Total"] = "총합"
L["Max"] = "최대"
L["World"] = "월드"
L["Realm"] = "서버"
L["Average"] = "평균"
L["Chance"] = "확률"
L["Reduction"] = "감소"
L["Auto"] = "자동"
L["Both"] = "모두"

L["Settings"] = "설정"
L["Melee"] = "근접"
L["MeleeDescription"] = ""
L["Defense"] = "방어"
L["DefenseDescription"] = ""
L["Ranged"] = "원거리"
L["RangedDescription"] = ""
L["Spell"] = "주문"
L["SpellDescription"] = ""
L["Resistance"] = "저항"
L["ResistanceDescription"] = ""
L["Misc"] = "기타"
L["MiscDescription"] = ""
L["Display_Average"] = "평균"
L["Display_AverageTip"] = ""
L["Display_Basic"] = "기본"
L["Display_BasicTip"] = ""
L["Display_MainHand"] = "주무기만 표시"
L["Display_MainHandTip"] = ""
