local AddName, AddonTable = ...

local L = AddonTable.RegisterLocale("enUS", true)

L["SpellPowerModifiers"] = "Spell Power Modifiers"
L["ShadowWeaving"] = "Shadow Weaving"
L["Misery"] = "Misery"
L["EbonPlague"] = "Ebon Plague"
L["ThundraStalker"] = "Tundra Stalker"
L["RageofRivendare"] = "Rage of Rivendare"
L["SurvivalofFittest"] = "Survival of the Fittest"
L["FaerieFire"] = "Faerie Fire"
L["InsectSwarm"] = "Insect Swarm"
L["EarthAndMoon"] = "Earth and Moon"
L["ImprovedFaerieFire"] = "Faerie Fire (improved)"
L["HuntersMark"] = "Hunter's Mark"	
L["ScorpidSting"] = "Scorpid Sting"
L["WintersChill"] = "Winter's Chill"
L["ImprovedScorch"] = "Improved Scorch"
L["FireVulnerability"] = "Fire Vulnerability"
L["HeartCrusader"] = "Heart of the Crusader"
L["Crusade"] = "Crusade"
L["Vengeance"] = "Vengeance"
L["Hemorrhage"] = "Hemorrhage"
L["SavageCombat"] = "Savage Combat"
L["MasterPoisoner"] = "Master Poisoner"
L["ExposeArmor"] = "Expose Armor"
L["Stormstrike"] = "Stormstrike"
L["TotemOfWrath"] = "Totem of Wrath"
L["SunderArmor"] = "Sunder Armor"
L["BloodFrenzy"] = "Blood Frenzy"
L["ShadowVulnerability"] = "Shadow Vulnerability"
L["ShadowMastery"] = "Shadow Mastery"
L["CurseofElements"] = "Curse of Elements"
L["CurseOfWeak"] = "Curse of Weakness"

L["TipsAndInfo"] = "Tips and Info!"
L["SinLive"] = "SinLive™ Stat!This stat is interactive and will scale with your current target!"
L["NPCPlus3"] = "+3 Levels"
L["NPC1to5"] = "+1 to +5 Levels"
L["NPCAnyLevel"] = "Any Level"
L["NPCSameLevel"] = "Same Level"	
L["DefaultValueText"] = "Default Value "
L["ScalingText"] = "Target Scaling "

L["CommonScaling"] = "This stat scales with on other stats"
L["Enhanced_BaseTooltip"] = "Enhanced provides the best accuracy by including talents, buffs, gems, enchants and much more " .. "Basic shows the basic value as displayed on the character panel, without any additions"
L["Percent_RatingTooltip"] = "Percentage displays the percentage value of this stat " .. "Rating displays the rating value of this stat"
L["Main_Off_HandTooltip"] = "Main-hand displays the Main-Hand value of this stat " .. "Off-hand displays the Off-Hand value of this stat"
L["Level_Same_BossTooltip"] = "Same Level displays the value against an NPC of the same level as yours " .. "Boss Level displays the value against an NPC of 1 to 5 level higher than yours"
L["Crit_Damage_TakenTooltip"] = "Crit Taken displays the reduction in periodic damage and in the chance to be critically hit " .. "Damage Taken displays the reduction in mana-drains effects and in the damage of critical strikes"
L["Chance_ReductionTooltip"] = "Chance displays the chance to be critically hit " .. "Reduction displays the reduction value to reach Crit immunity"
L["Total_RatingTooltip"] = "Total displays the total Defense value, that includes the base and the bonus " .. "Rating displays the rating value of this stat"
L["Max_Average_DamageTooltip"] = "Max displays maximum damage value " .. "Average switches from max values to average values"
L["Regen_Normal_CastingTooltip"] = "Normal displays the mana regeneration outside of the 5-second rule, while not casting " .. "Casting displays the mana regeneration while casting"
L["World_RealmTooltip"] = "Realm displays the average latency of the connection from your computer to the Blizzard server in milliseconds" .. "World displays the in-game latency of the connection from your computer to the Game World"
L["Main_Off_AutoTooltip"] = "Main-hand displays the Main-Hand value of this stat " .. "Off-hand displays the Off-Hand value of this stat " .. "Auto automatically detects if you're wielding a 1H or 2H and displays the stat accordingly"
L["Display_MainHandTooltip"] = "Main-Hand Only disables the automatic display of the Off-hand value, if applicable"
L["Display_AverageTooltip"] = "Average switches from max to average values"
L["Display_BasicTooltip"] = "Basic shows the basic value as displayed on the character panel, without any additions"

L["AP"] = "AP"
L["APAbrev"] = "AP"
L["APMenu"] = "Attack Power"
L["APTip"] = ""
L["APDescription"] = "Melee Attack Power " .. "Attack Power value in red indicates that you are affected by a debuff"

L["DMG"] = "Damage"
L["DMGAbrev"] = "DMG"
L["DMGMenu"] = "Damage"
L["DMGTip"] = ""
L["DMGDescription"] = "Damage value in red indicates that you are affected by a debuff related to this stat" 

L["mDPS"] = "DPS"
L["mDPSAbrev"] = "DPS"
L["mDPSMenu"] = "DPS"
L["mDPSTip"] = ""
L["mDPSDescription"] = "DPS value in red indicates that you are affected by a debuff" .. "This stat will scale with your Attack Speed and Damage values"

L["Crit"] = "Crit"
L["CritAbrev"] = "Crit"
L["CritMenu"] = "Critical Chance"
L["CritTip"] = ""
L["CritDescription"] = "Spell book Critical Strike value. Also represents your Critical Strike in PvP"

L["CritBoss"] = "Crit+"
L["CritBossAbrev"] = "Crit+"
L["CritBossMenu"] = "Critical vs Boss"
L["CritBossTip"] = ""
L["CritBossDescription"] = "Critical Strike value in PvE, against higher level NPCs. Includes all Crit Suppressions auras"

L["CritCap"] = "Crit Cap"
L["CritCapAbrev"] = "Cap"
L["CritCapMenu"] = "Critical Cap"
L["CritCapTip"] = ""
L["CritCapDescription"] = "Displays the Critical Strike Cap against a Boss level. This stat will scale based on the weapons used" .. "Crit Cap value in red indicates that you have reached the Critical cap"

L["Hit"] = "Hit"
L["HitAbrev"] = "Hit"
L["HitMenu"] = "Hit"
L["HitTip"] = ""
L["HitDescription"] = "Hit Chance displayed in percentage, rating or both " .. "Hit value in green indicates that you have reached your Hit cap"

L["HasteMelee"] = "Haste"
L["HasteMeleeAbrev"] = "Has"
L["HasteMeleeMenu"] = "Haste"
L["HasteMeleeTip"] = ""
L["HasteMeleeDescription"] = "Haste displayed in percentage, rating or both"

L["weaponSpeed"] = "Atk Speed"
L["weaponSpeedAbrev"] = "As"
L["weaponSpeedMenu"] = "Weapon Speed"
L["weaponSpeedTip"] = ""
L["weaponSpeedDescription"] = "Weapon speed displayed as Main-Hand, Off-Hand or Auto"

L["Expertise"] = "Expertise"
L["ExpertiseAbrev"] = "Exp"
L["ExpertiseMenu"] = "Expertise"
L["ExpertiseTip"] = ""
L["ExpertiseDescription"] = "Expertise - chance to be dodged or parried in percentage, rating or both " .. "Expertise value in green indicates that you have reached your Expertise cap"

L["ArmorPen"] = "Armor Pen"
L["ArmorPenAbrev"] = "ArP"
L["ArmorPenMenu"] = "Penetration"
L["ArmorPenTip"] = ""
L["ArmorPenDescription"] = "Target's armor value ignored by your physical attacks in percentage, rating or both"

L["NPCArmor"] = "Armor+"
L["NPCArmorAbrev"] = "Arm+"
L["NPCArmorMenu"] = "Boss Armor"
L["NPCArmorTip"] = ""
L["NPCArmorDescription"] = "Armor value of a raid boss NPC of up to +3 levels. A target must be selected for its armor to be displayed"

L["BossReduc"] = "DMG-"
L["BossReducAbrev"] = "DMG-"
L["BossReducMenu"] = "DMG Reduction"
L["BossReducTip"] = ""
L["BossReducDescription"] = "Percentage of reduction to physical damage done against a Raid Boss NPC based on its armorWhen targeting a non-Raid Boss NPC, the total value of armor reduction debuffs will be shownA target must be selected to see the reduction value" .. L["ScalingText"] .. L["NPCPlus3"] .. L["SunderArmor"] .. L["ExposeArmor"] .. L["FaerieFire"] .. L["CurseOfWeak"]

L["MeleeMiss"] = "Miss"
L["MeleeMissAbrev"] = "Miss"
L["MeleeMissMenu"] = "Miss Chance"
L["MeleeMissTip"] = ""
L["MeleeMissDescription"] = "Miss chance with melee weapons against NPCs of your level, boss levels or both"

L["Avoidance"] = "Avoidance"
L["AvoidanceAbrev"] = "Avoid"
L["AvoidanceMenu"] = "Avoidance"
L["AvoidanceTip"] = ""
L["AvoidanceDescription"] = "Chance to avoid Crushing Blows " .. "Avoidance value in green indicates that you are uncrushable"

L["Crushing"] = "Crushing"
L["CrushingAbrev"] = "Crush"
L["CrushingMenu"] = "Crushing"
L["CrushingTip"] = ""
L["CrushingDescription"] = "Chance to hit by a Crushing Blow " .. "Crushing value in green indicates that you are uncrushable"

L["CritReceived"] = "Crit-"
L["CritReceivedAbrev"] = "Crit-"
L["CritReceivedMenu"] = "Crit Immunity" 
L["CritReceivedTip"] = "" .. "Crtically Hit value in red indicates that you are under the critical hit cap" .. L["DefaultValueText"] .. L["NPCPlus3"] .. L["ScalingText"] .. L["NPCAnyLevel"] .. L["SurvivalofFittest"]

L["Resilience"] = "Resilience"
L["ResilienceAbrev"] = "Res"
L["ResilienceMenu"] = "Resilience"
L["ResilienceTip"] = ""
L["ResilienceDescription"] = "Resilience displayed in critical taken, damage taken or both"

L["Armor"] = "Armor"
L["ArmorAbrev"] = "Arm"
L["ArmorMenu"] = "Armor"
L["ArmorTip"] = ""
L["ArmorDescription"] = "Effective Armor including its modifiers " .. "Armor value in red indicates that you are affected by a debuff related to this stat"	

L["Mitigation"] = "Mitigation"
L["MitigationAbrev"] = "Mit"
L["MitigationMenu"] = "Mitigation"
L["MitigationTip"] = ""
L["MitigationDescription"] = "Percentage of damage reduction " .. "Mitigation value in green indicates that you have reached the Mitigation cap"

L["DefenseStat"] = "Defense"
L["DefenseStatAbrev"] = "Def"
L["DefenseStatMenu"] = "Defense"
L["DefenseStatTip"] = ""
L["DefenseStatDescription"] = "Defense displayed in total, rating or both " .. "Defense value in green indicates that you have reached the Defense cap against a raid boss"

L["HitReduction"] = "Hit-"
L["HitReductionAbrev"] = "Hit-"
L["HitReductionMenu"] = "Hit Reduction"
L["HitReductionTip"] = ""
L["HitReductionDescription"] = "Percentage reduction to be hit by physical attacks from talents and debuffs "

L["Dodge"] = "Dodge"
L["DodgeAbrev"] = "Dod"
L["DodgeMenu"] = "Dodge"
L["DodgeTip"] = ""
L["DodgeDescription"] = "Chance to Dodge an attack, displayed in percentage, rating or both"

L["Parry"] = "Parry"
L["ParryAbrev"] = "Par"
L["ParryMenu"] = "Parry"
L["ParryTip"] = ""
L["ParryDescription"] = "Chance to Parry an attack, displayed in percentage, rating or both"

L["Block"] = "Block"
L["BlockAbrev"] = "Blo"
L["BlockMenu"] = "Block"
L["BlockTip"] = ""
L["BlockDescription"] = "Chance to Block an attack, displayed in percentage, rating or both"

L["RAP"] = "Ranged AP"
L["RAPAbrev"] = "rAP"
L["RAPMenu"] = "Attack Power"
L["RAPTip"] = ""
L["RAPDescription"] = "Ranged Attack Power "  .. "Attack Power value in red indicates that you are affected by a debuff" .. "Attack Power value in green indicates that Hunter's Mark ability is applied on your target"

L["RDMG"] = "Ranged DMG"
L["RDMGAbrev"] = "rDMG"
L["RDMGMenu"] = "Damage"
L["RDMGTip"] = ""
L["RDMGDescription"] = "Damage value in red indicates that you are affected by a debuff related to this stat"

L["rDPS"] = "Ranged DPS"
L["rDPSAbrev"] = "rDPS"
L["rDPSMenu"] = "DPS"
L["rDPSTip"] = ""
L["rDPSDescription"] = "Damage per second displayed in max, average of both " .. "DPS in red indicates that you are affected by a debuff" .. "This stat will scale with your Attack Speed and Damage values"

L["RangedCrit"] = "Ranged Crit"
L["RangedCritAbrev"] = "rCrit"
L["RangedCritMenu"] = "Critical Chance"
L["RangedCritTip"] = ""
L["RangedCritDescription"] = "Critical Strike value. Also represents your Critical Strike in PvP"

L["RangedCritBoss"] = "Ranged Crit+"
L["RangedCritBossAbrev"] = "rCrit+"
L["RangedCritBossMenu"] = "Critical vs Boss"
L["RangedCritBossTip"] = ""
L["RangedCritBossDescription"] = "Critical Strike value in PvE, against higher level NPCs. Includes all Crit Suppressions auras"

L["RangedHit"] = "Ranged Hit"
L["RangedHitAbrev"] = "Hit"
L["RangedHitMenu"] = "Hit"
L["RangedHitTip"] = ""
L["RangedHitDescription"] = "Hit Chance displayed in percentage, rating or both " .. "Hit value in green indicates that you have reached your Hit cap"

L["HasteRanged"] = "Ranged Haste"
L["HasteRangedAbrev"] = "rHas"
L["HasteRangedMenu"] = "Haste"
L["HasteRangedTip"] = ""
L["HasteRangedDescription"] = "Haste displayed in percentage, rating or both"

L["RangedPen"] = "Ranged Pen"
L["RangedPenAbrev"] = "rArP"
L["RangedPenMenu"] = "Penetration"
L["RangedPenTip"] = ""
L["RangedPenDescription"] = "Percentage of your target's armor ignored by your physical attacks"

L["rangedSpeed"] = "Ranged Atk Speed"
L["rangedSpeedAbrev"] = "rAs"
L["rangedSpeedMenu"] = "Attack Speed"
L["rangedSpeedTip"] = ""
L["rangedSpeedDescription"] = "Weapon speed of the equipped range weapon"

L["RangedMiss"] = "rMiss"
L["RangedMissAbrev"] = "rMiss"
L["RangedMissMenu"] = "Miss Chance"
L["RangedMissTip"] = ""
L["RangedMissDescription"] = "Miss chance with ranged weapons against NPCs of your level, boss levels or both"

L["Fire"] = "Fire"
L["FireAbrev"] = "Fire"
L["FireMenu"] = "Fire Power"
L["FireTip"] = ""
L["FireDescription"] = "Fire spell damage"

L["Frost"] = "Frost"
L["FrostAbrev"] = "Fro"
L["FrostMenu"] = "Frost Power"
L["FrostTip"] = ""
L["FrostDescription"] = "Frost spell damage"

L["Arcane"] = "Arcane"
L["ArcaneAbrev"] = "Arc"
L["ArcaneMenu"] = "Arcane Power"
L["ArcaneTip"] = ""
L["ArcaneDescription"] = "Arcane spell damage"

L["Shadow"] = "Shadow"
L["ShadowAbrev"] = "Sha"
L["ShadowMenu"] = "Shadow Power"
L["ShadowTip"] = ""
L["ShadowDescription"] = "Shadow spell damage"

L["Nature"] = "Nature"
L["NatureAbrev"] = "Nat"
L["NatureMenu"] = "Nature Power"
L["NatureTip"] = ""
L["NatureDescription"] = "Nature spell damage"

L["Healing"] = "Healing"
L["HealingAbrev"] = "Heal"
L["HealingMenu"] = "Healing Power"
L["HealingTip"] = ""
L["HealingDescription"] = "Healing spell power"

L["Holy"] = "Holy"
L["HolyAbrev"] = "Holy"
L["HolyMenu"] = "Holy Power"
L["HolyTip"] = ""
L["HolyDescription"] = "Holy damage"

L["SpellCrit"] = "Spell Crit"
L["SpellCritAbrev"] = "sCrit"
L["SpellCritMenu"] = "Critical Chance"
L["SpellCritTip"] = ""
L["SpellCritDescription"] = "Critical Strike value in percentage, rating or both. Also represents your Critical Strike in PvPSpell-specific Crit Talents are colored and will appear next to the current value"

L["SpellCritBoss"] = "Spell Crit+"
L["SpellCritBossAbrev"] = "sCrit+"
L["SpellCritBossMenu"] = "Critical vs Boss"
L["SpellCritBossTip"] = ""
L["SpellCritBossDescription"] = "Critical Strike value in PvE, against higher level NPCs. Includes all Crit Suppressions auras"

L["SpellHit"] = "Spell Hit"
L["SpellHitAbrev"] = "spHit"
L["SpellHitMenu"] = "Hit"
L["SpellHitTip"] = ""
L["SpellHitDescription"] = "Hit chance displayed in percentage, rating or both"

L["HasteCaster"] = "Spell Haste"
L["HasteCasterAbrev"] = "sHas"
L["HasteCasterMenu"] = "Haste"
L["HasteCasterTip"] = ""
L["HasteCasterDescription"] = "Haste displayed in percentage, rating or both"

L["SpellPenetration"] = "Spell Pen"
L["SpellPenetrationAbrev"] = "sPen"
L["SpellPenetrationMenu"] = "Penetration"
L["SpellPenetrationTip"] = ""
L["SpellPenetrationDescription"] = "Percentage of your target's spell resistance ignored by your spells"

L["SpellMiss"] = "Spell Miss"
L["SpellMissAbrev"] = "sMis"
L["SpellMissMenu"] = "Miss Chance"
L["SpellMissTip"] = ""
L["SpellMissDescription"] = "Miss chance with spells against NPCs of your level, boss levels or both"

L["ManaRegen"] = "MP2"
L["ManaRegenAbrev"] = "MP2"
L["ManaRegenMenu"] = "MP2"
L["ManaRegenTip"] = ""
L["ManaRegenDescription"] = "Mana Regeneration per 2 seconds"

L["MP5"] = "MP5"
L["MP5Abrev"] = "MP5"
L["MP5Menu"] = "MP5"
L["MP5Tip"] = ""
L["MP5Description"] = "Mana Regeneration per 5 seconds"

L["FireResist"] = "Fire Res"
L["FireResistAbrev"] = "Fr"
L["FireResistMenu"] = "Fire"
L["FireResistTip"] = ""
L["FireResistDescription"] = "Resistance value against Fire spell damage"

L["FrostResist"] = "Frost Res"
L["FrostResistAbrev"] = "FrR"
L["FrostResistMenu"] = "Frost"
L["FrostResistTip"] = ""
L["FrostResistDescription"] = "Resistance value against Frost spell damage"

L["ShadowResist"] = "Shadow Res"
L["ShadowResistAbrev"] = "Sr"
L["ShadowResistMenu"] = "Shadow"
L["ShadowResistTip"] = ""
L["ShadowResistDescription"] = "Resistance value against Shadow spell damage"

L["ArcaneResist"] = "Arcane Res"
L["ArcaneResistAbrev"] = "ArR"
L["ArcaneResistMenu"] = "Arcane"
L["ArcaneResistTip"] = ""
L["ArcaneResistDescription"] = "Resistance value against Arcane spell damage"

L["NatureResist"] = "Nature Res"
L["NatureResistAbrev"] = "Nr"
L["NatureResistMenu"] = "Nature"
L["NatureResistTip"] = ""
L["NatureResistDescription"] = "Resistance value against Nature spell damage"

L["ItemLevel"] = "Item Level"
L["ItemLevelAbrev"] = "iLvl"
L["ItemLevelMenu"] = "Item Level"
L["ItemLevelTip"] = ""
L["ItemLevelDescription"] = "Average item level of currently equipped gear"

L["Speed"] = "Speed"
L["SpeedAbrev"] = "Spe"
L["SpeedMenu"] = "Speed"
L["SpeedTip"] = ""
L["SpeedDescription"] = "The current movement speed of your character, in real-time " .. "Speed value in red indicates that you are affected by slowing effects or moving at a slower speed than normal"

L["TargetSpeed"] = "Target Speed"
L["TargetSpeedAbrev"] = "Spe+"
L["TargetSpeedMenu"] = "Target Speed"
L["TargetSpeedTip"] = ""
L["TargetSpeedDescription"] = "The current movement speed of your target, in real-time " .. "Speed value in red indicates that your target is affected by slowing effects or moving at a slower speed than normal "

L["Durability"] = "Durability"
L["DurabilityAbrev"] = "Dur"
L["DurabilityMenu"] = "Durability"
L["DurabilityTip"] = ""
L["DurabilityDescription"] = "Durability percentage of your currently equipped gear and weapons"

L["BuffCounter"] = "Buffs"
L["BuffCounterAbrev"] = "Buf"
L["BuffCounterMenu"] = "Player Buffs"
L["BuffCounterTip"] = ""
L["BuffCounterDescription"] = "Total number of beneficial auras applied to your character"

L["DebuffCounter"] = "Debuffs"
L["DebuffCounterAbrev"] = "Deb"
L["DebuffCounterMenu"] = "Target Debuffs"
L["DebuffCounterTip"] = ""
L["DebuffCounterDescription"] = "Total number of non-beneficial auras (debuffs) applied to your current target " .. L["ScalingText"] .. "Targeted NPC"

L["Lag"] = "Ping"
L["LagAbrev"] = "Ping"
L["LagMenu"] = "Ping"
L["LagTip"] = ""
L["LagDescription"] = "Connection latency (Ping)"

L["FPS"] = "FPS"
L["FPSAbrev"] = "FPS"
L["FPSMenu"] = "FPS"
L["FPSTip"] = ""
L["FPSDescription"] = "Frames per second [FPS]"

L["Money"] = "Gold"
L["MoneyAbrev"] = "G"
L["MoneyMenu"] = "Money"
L["MoneyTip"] = ""
L["MoneyDescription"] = "Total amount of money in your character's possession"


-- Fonts
L["Default Font"] = "Friz Quadrata TT"
L["Thin"] = "Thin"
L["Thick"] = "Thick"
L["Monochrome"] = "Monochrome"
L["Thin Monochrome"] = "Thin Monochrome"
L["Thick Monochrome"] = "Thick Monochrome"
L["None"] = "None"



	------------------
	--    Config    --
	------------------

-- Settings tabs
L["HUDMenu"] = "General"
L["FontsMenu"] = "Fonts"
L["DisplayMenu"] = "Display"
L["ProfilesMenu"] = "Profiles"

-- Settings HUD
L["SettingsDescription"] = ""
L["HideHUD"] = "Hide"
L["HideHUDTip"] = "Hide, Lock or Reset the stats HUD's position"
L["LockHUD"] = "Lock"
L["LockHUDTip"] = ""
L["ResetPosition"] = "Reset Position"
L["ResetPositionTip"] = ""
L["MinimapGroupText"] = "Minimap"
L["Minimap"] = "Show"
L["MinimapTip"] = "Show or Hide the Minimap button. Hover to see quick access options"

-- Fonts Settings
L["StatFontTip"] = "Fonts"
L["StatFontSizeTip"] = "Font Size"
L["StatFontFlagsTip"] = "Outline"

-- Display Settings
L["StatIconsTip"] = "Toggle icons on stats"
L["StatIcons"] = "Icons"
L["StatTextAbreviateTip"] = "Abbreviate stat name"
L["StatTextAbreviate"] = "Abbreviate"
L["StatTextCapsTip"] = "Toggle caps text"
L["StatTextCaps"] = "All caps"
L["GroupOrderTip"] = "Order stats by group"
L["GroupOrder"] = "Group order"
L["VerticalGroupText"] = "Alignment and Spacing"
L["VerticalTip"] = "Vertical & Horizontal"
L["Vertical"] = "Vertical"
L["StatSpacingHTip"] = "Horizontal Spacing"
L["StatSpacingVTip"] = "Vertical Spacing"
L["StatAlignmentTip"] = "Alignment"
L["StatRowsTip"] = "Rows"

-- Minimap
L["LeftClick"] = "Quick Access"
L["OpenClose"] = ""
L["RightClick"] = "Right Click"
L["EnableDisable"] = "Enable/Disable the HUD"
L["ShiftRightClick"] = "Shift + Right Click"
L["UnlockHUD"] = "Unlock the HUD"

-- Settings Profile
L["Selected"] = "Apply"
L["SelectProfile"] = "Manage your profiles: Select, Create, Copy or Delete. Profiles in-use by a character cannot be deleted. A different profile must be selected first."
L["ProfileSelected"] = "Profiles"
L["ProfileUsed"] = "Profile is currently in use, unable to delete!"
L["NewProfile"] = "New Profile"
L["CurrentProfile"] = "Active Profile"
L["Copy"] = "Apply"
L["Delete"] = "Delete"
L["ConfirmDelete"] = "Confirm"
L["Cancel"] = "Cancel"
L["ProfileCopyDelete"] = "Select, delete or copy to new profile."

-- Settings Options
L["OptionsTip"] = "Extended Options"
L["Show"] = "Show"
L["ShowTip"] = ""
L["Enhanced"] = "Enhanced"
L["Basic"] = "Basic"
L["Damage"] = "Damage"
L["DamageTaken"] = "Damage Taken"
L["Percentage"] = "Percentage"
L["Rating"] = "Rating"
L["MainHand"] = "Main-Hand"
L["OffHand"] = "Off-Hand"
L["SameLevel"] = "Same Level"
L["BossLevel"] = "Boss Level"
L["Regen"] = "Normal Regen"
L["OutOfCombat"] = "Normal"
L["Casting"] = "Casting"
L["CritTaken"] = "Crit taken"
L["Total"] = "Total"
L["Max"] = "Max"
L["World"] = "World"
L["Realm"] = "Realm"
L["Average"] = "Average"
L["Chance"] = "Chance"
L["Reduction"] = "Reduction"
L["Auto"] = "Auto"
L["Both"] = "Both"

L["Settings"] = "Settings"
L["Melee"] = "Melee"
L["MeleeDescription"] = ""
L["Defense"] = "Defense"
L["DefenseDescription"] = ""
L["Ranged"] = "Ranged"
L["RangedDescription"] = ""
L["Spell"] = "Spell"
L["SpellDescription"] = ""
L["Resistance"] = "Resistance"
L["ResistanceDescription"] = ""
L["Misc"] = "Misc"
L["MiscDescription"] = ""
L["Display_Average"] = "Average"
L["Display_AverageTip"] = ""
L["Display_Basic"] = "Basic"
L["Display_BasicTip"] = ""
L["Display_MainHand"] = "Main-Hand Only"
L["Display_MainHandTip"] = ""
